/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gas.telas;

/**
 *
 * @author Gabriel Augusto
 */
public class ParanUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ParanUsuario
     */
    public ParanUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        chkInativarUsuario = new javax.swing.JCheckBox();
        chkResetSenha = new javax.swing.JCheckBox();
        chkCadVolun = new javax.swing.JCheckBox();
        chkAlterDadosVolun = new javax.swing.JCheckBox();
        chkCadFamilia = new javax.swing.JCheckBox();
        chkCadMorador = new javax.swing.JCheckBox();
        chkExcDoacao = new javax.swing.JCheckBox();
        chkAlterDadosFamilia = new javax.swing.JCheckBox();
        chkAlterDadosMorador = new javax.swing.JCheckBox();
        chkAlterConfigSistema = new javax.swing.JCheckBox();
        chkGerarRelatorio = new javax.swing.JCheckBox();
        chkCadDoacao = new javax.swing.JCheckBox();
        chkAlterDoacao = new javax.swing.JCheckBox();
        chkGerenUsuario = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnDesabilitarTodos = new javax.swing.JButton();
        btnHabilitarTodos = new javax.swing.JButton();

        setTitle("Permissões de Usuário");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Login:");

        jButton1.setText("...");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkInativarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkInativarUsuario.setText("Inativo");

        chkResetSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkResetSenha.setText("Resetar a Senha");

        chkCadVolun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkCadVolun.setText("Cadastra Voluntário");

        chkAlterDadosVolun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkAlterDadosVolun.setText("Altera Dados de Voluntário");

        chkCadFamilia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkCadFamilia.setText("Cadastra Família");

        chkCadMorador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkCadMorador.setText("Cadastra Morador");

        chkExcDoacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkExcDoacao.setText("Excluir Doações");

        chkAlterDadosFamilia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkAlterDadosFamilia.setText("Altera Dados da Família");

        chkAlterDadosMorador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkAlterDadosMorador.setText("Altera Dados do Morador");

        chkAlterConfigSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkAlterConfigSistema.setText("Altera Configurações do Sistema");

        chkGerarRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkGerarRelatorio.setText("Gerar Relatórios");

        chkCadDoacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkCadDoacao.setText("Cadastra Doações");

        chkAlterDoacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkAlterDoacao.setText("Altera Doações");

        chkGerenUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkGerenUsuario.setText("Gerenciar Usuário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chkInativarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(chkResetSenha))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chkAlterConfigSistema)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkGerarRelatorio))
                                    .addComponent(chkGerenUsuario))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCadDoacao)
                                    .addComponent(chkAlterDoacao)
                                    .addComponent(chkExcDoacao)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCadVolun)
                                    .addComponent(chkAlterDadosVolun))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCadFamilia)
                                    .addComponent(chkAlterDadosFamilia))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCadMorador)
                                    .addComponent(chkAlterDadosMorador))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkInativarUsuario)
                    .addComponent(chkResetSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCadVolun)
                            .addComponent(chkCadMorador)))
                    .addComponent(chkCadFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkAlterDadosVolun)
                            .addComponent(chkAlterDadosFamilia))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chkAlterDadosMorador)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAlterConfigSistema)
                    .addComponent(chkGerarRelatorio)
                    .addComponent(chkCadDoacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAlterDoacao)
                    .addComponent(chkGerenUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkExcDoacao)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTextField2.setEnabled(false);

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");

        btnDesabilitarTodos.setText("Desabilitar Todos");
        btnDesabilitarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesabilitarTodosActionPerformed(evt);
            }
        });

        btnHabilitarTodos.setText("Habilitar Todos");
        btnHabilitarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHabilitarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesabilitarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHabilitarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesabilitarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnHabilitarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarTodosActionPerformed
    
        chkAlterConfigSistema.setSelected(true);
        chkAlterDadosFamilia.setSelected(true);
        chkAlterDadosMorador.setSelected(true);
        chkAlterDadosVolun.setSelected(true);
        chkAlterDoacao.setSelected(true);
        chkCadDoacao.setSelected(true);
        chkCadFamilia.setSelected(true);
        chkCadMorador.setSelected(true);
        chkCadVolun.setSelected(true);
        chkExcDoacao.setSelected(true);
        chkGerarRelatorio.setSelected(true);
        chkGerenUsuario.setSelected(true);
        

    }//GEN-LAST:event_btnHabilitarTodosActionPerformed

    private void btnDesabilitarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesabilitarTodosActionPerformed
        
        chkAlterConfigSistema.setSelected(false);
        chkAlterDadosFamilia.setSelected(false);
        chkAlterDadosMorador.setSelected(false);
        chkAlterDadosVolun.setSelected(false);
        chkAlterDoacao.setSelected(false);
        chkCadDoacao.setSelected(false);
        chkCadFamilia.setSelected(false);
        chkCadMorador.setSelected(false);
        chkCadVolun.setSelected(false);
        chkExcDoacao.setSelected(false);
        chkGerarRelatorio.setSelected(false);
        chkGerenUsuario.setSelected(false);
        
        
        
    }//GEN-LAST:event_btnDesabilitarTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesabilitarTodos;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnHabilitarTodos;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox chkAlterConfigSistema;
    private javax.swing.JCheckBox chkAlterDadosFamilia;
    private javax.swing.JCheckBox chkAlterDadosMorador;
    private javax.swing.JCheckBox chkAlterDadosVolun;
    private javax.swing.JCheckBox chkAlterDoacao;
    private javax.swing.JCheckBox chkCadDoacao;
    private javax.swing.JCheckBox chkCadFamilia;
    private javax.swing.JCheckBox chkCadMorador;
    private javax.swing.JCheckBox chkCadVolun;
    private javax.swing.JCheckBox chkExcDoacao;
    private javax.swing.JCheckBox chkGerarRelatorio;
    private javax.swing.JCheckBox chkGerenUsuario;
    private javax.swing.JCheckBox chkInativarUsuario;
    private javax.swing.JCheckBox chkResetSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
